### ISSUE TITLE
When are we going to push changes from fix_half_tests_on_new_hip branch to master

### ISSUE THREAD

**Issue by rkothako** [ROCmSoftwarePlatform/rocPRIM#17] opened 2018-07-30 03:43 UTC

**Comment by ex-rzr** [comment] 2018-08-02 06:16
Currently these changes are merged into `develop` branch (which also contains some changes for the latest HIP versions).

**Comment by rkothako** [comment] 2018-08-02 08:56
Thanks. Please let know once the changes are in master branch.
We are taking code from master only, mostly, hence this request.

**Comment by ncrkblacksmith** [comment] 2018-08-29 12:57
The requested changes have been pushed to the master branch.

**Comment by ncrkblacksmith** [comment] 2018-08-29 12:59
Can we remove the `fix_half_tests_on_new_hip` branch?

**Comment by rkothako** [comment] 2018-08-29 13:00
Thanks for pushing to master.
I will validate in few mins and update you please....

**Comment by rkothako** [comment] 2018-08-29 13:25
@ncrkblacksmith 
I have observed that test count decreased from around 90 to 55, is it expected?

**Comment by jszuppe** [comment] 2018-08-29 13:59
@rkothako That's for reporting that. We will fix that, it's unexpected change caused by other PRs merge for compatibility with hip-clang (hcc tests were disabled). We will update `master` and `develop` today to address that.

**Comment by jszuppe** [comment] 2018-08-29 14:17
@rkothako It's fixed. CI didn't complain there was less tests, so we missed that problem. Thanks again!

**Comment by rkothako** [comment] 2018-08-29 14:53
Wonderful. all tests are PASSING on VEGA10 and VEGA20.

**Comment by jszuppe** [comment] 2018-08-30 07:52
I'll remove `fix_half_tests_on_new_hip` later today.

**Closed** 2018-08-30 20:05 UTC
