### ISSUE TITLE
rocPRIM 5.4.3 failed device_adjacent_difference on gfx906

### ISSUE THREAD

**Issue by littlewu2508** [ROCmSoftwarePlatform/rocPRIM#415] opened 2023-03-19 07:36 UTC
**Describe the bug**
On Radeon VII, rocPRIM 5.4.3 failed one test suite: device_adjacent_difference:
```
[ RUN      ] RocprimDeviceAdjacentDifferenceLargeTests/0.LargeIndices
/fast/portage/sci-libs/rocPRIM-5.4.3/work/rocPRIM-rocm-5.4.3/test/rocprim/test_device_adjacent_difference.cpp:556: Failure
Expected equality of these values:
  incorrect_flag
    Which is: 1
  0
Google Test trace:
/fast/portage/sci-libs/rocPRIM-5.4.3/work/rocPRIM-rocm-5.4.3/test/rocprim/test_device_adjacent_difference.cpp:495: with size = 3860949257
/fast/portage/sci-libs/rocPRIM-5.4.3/work/rocPRIM-rocm-5.4.3/test/rocprim/test_device_adjacent_difference.cpp:489: with seed= 1649760492
/fast/portage/sci-libs/rocPRIM-5.4.3/work/rocPRIM-rocm-5.4.3/test/rocprim/test_device_adjacent_difference.cpp:481: is_left = true, is_in_place = false
/fast/portage/sci-libs/rocPRIM-5.4.3/work/rocPRIM-rocm-5.4.3/test/rocprim/test_device_adjacent_difference.cpp:469: with device_id= 0
[  FAILED  ] RocprimDeviceAdjacentDifferenceLargeTests/0.LargeIndices, where TypeParam = DeviceAdjacentDifferenceLargeParams<true, false> (67 ms)
```

**Log-files**
The full build log: 
[build.log.gz](https://github.com/ROCmSoftwarePlatform/rocPRIM/files/11010451/build.log.gz)

Log of tests:
[LastTest.log.gz](https://github.com/ROCmSoftwarePlatform/rocPRIM/files/11010452/LastTest.log.gz)

**Environment**

Attach `environment.txt`: [environment.txt](https://github.com/ROCmSoftwarePlatform/rocPRIM/files/11010454/environment.txt)

**Comment by Snektron** [comment] 2023-03-22 18:51
I have been able to reproduce this on our Vega 20. Not sure yet what the problem is, but will look into it.

**Comment by Snektron** [comment] 2023-03-24 18:17
It looks like this issue is caused by a number of factors coming together:
- Gentoo uses upstream clang instead of AMD's fork, [ROCm clang](https://github.com/RocmSoftwarePlatform/llvm-project). (As far as I know there is no guarantee that things should work with upstream, but I will just assume that Gentoo maintainers know what they are doing here.)
- Upstream clang seems to miscompile `assert` in device code.
- rocPRIM has some `asserts` in the device code related to `device_adjacent_difference`, which are here:
  https://github.com/ROCmSoftwarePlatform/rocPRIM/blob/a6c75302f0e526ac1bdb25e91f1c02115e0658dd/rocprim/include/rocprim/block/detail/block_adjacent_difference_impl.hpp#L170
  and here:
  https://github.com/ROCmSoftwarePlatform/rocPRIM/blob/a6c75302f0e526ac1bdb25e91f1c02115e0658dd/rocprim/include/rocprim/block/detail/block_adjacent_difference_impl.hpp#L291

Interestingly, the blocks where the error manifests itself do not even pass that assert. Furthermore, leaving in the `assert` for the `subtract_right_partial` function, which is not part of the test that fails and not even compiled in if all the tests but the failing test are enabled, the test still fails.

I can dig into this a little deeper to find out why ROCm clang works fine for this later and/or produce a proper fix for this in rocPRIM. It'll be a while before that lands in any official version of ROCm though. For the immediate future, I suggest to `sed` out the asserts in your `ebuild` or apply the following patch:

```diff
Author: Robin Voetter <robin@streamhpc.com>
Date:   Fri Mar 24 19:12:01 2023 +0100

    block adjacent difference: remove asserts
    
    These asserts seem to cause a miscompilation if compiling with upstream clang
    15 while not enabling -DNDEBUG, which causes some device_adjacent_difference
    tests to fail.

diff --git a/rocprim/include/rocprim/block/detail/block_adjacent_difference_impl.hpp b/rocprim/include/rocprim/block/detail/block_adjacent_difference_impl.hpp
index 6d41d450..8508e2a8 100644
--- a/rocprim/include/rocprim/block/detail/block_adjacent_difference_impl.hpp
+++ b/rocprim/include/rocprim/block/detail/block_adjacent_difference_impl.hpp
@@ -167,8 +167,6 @@ public:
         static constexpr auto as_flags = bool_constant<AsFlags> {};
         static constexpr auto reversed = bool_constant<Reversed> {};
 
-        assert(valid_items <= BlockSize * ItemsPerThread);
-
         const unsigned int flat_id
             = ::rocprim::flat_block_thread_id<BlockSizeX, BlockSizeY, BlockSizeZ>();
 
@@ -288,8 +286,6 @@ public:
         static constexpr auto as_flags = bool_constant<AsFlags> {};
         static constexpr auto reversed = bool_constant<Reversed> {};
 
-        assert(valid_items <= BlockSize * ItemsPerThread);
-
         const unsigned int flat_id
             = ::rocprim::flat_block_thread_id<BlockSizeX, BlockSizeY, BlockSizeZ>();
```

**Comment by littlewu2508** [comment] 2023-03-25 04:24
> It looks like this issue is caused by a number of factors coming together:
> 
>     * Gentoo uses upstream LLVM instead of AMD's fork, [ROCm LLVM](https://github.com/RocmSoftwarePlatform/llvm-project). (As far as I know there is no guarantee that things should work with upstream, but I will just assume that Gentoo maintainers know what they are doing here.)

Exactly. And using upstream clang in ROCm stack is adopted by other distributions' official packages (Debian and Fedora). We know there can be problems and that's why we keep running tests.

>     * Upstream clang seems to miscompile `assert` in device code.

According to your description, it does seems that upstream clang has some misbehavior in compiling `assert`.  I suggest report to llvm/clang once we confirm this.

> For the immediate future, I suggest to sed out the asserts in your ebuild or apply the following patch:

Thanks for your suggestion!

**Comment by doctorcolinsmith** [comment] 2023-04-03 15:24
Closing this as the user has a patch to work around the problem.  We will follow up internally with the AMD compiler team.

**Closed by doctorcolinsmith** 2023-04-03 15:24 UTC
